apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: butterfly
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 32
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        terminationGracePeriodSeconds: 5
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: role
                        operator: In
                        values:
                          - leader
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: butterfly-leader
            image: ghcr.io/abatilo/butterfly:latest
            imagePullPolicy: Always
            command:
              - process_allocator
            resources:
              limits:
                nvidia.com/gpu: "1"
            volumeMounts:
              - name: dshm
                mountPath: /dev/shm
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
    workerTemplate:
      metadata:
        labels:
          role: worker
      spec:
        terminationGracePeriodSeconds: 5
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: role
                        operator: In
                        values:
                          - worker
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: butterfly-worker
            image: ghcr.io/abatilo/butterfly:latest
            imagePullPolicy: Always
            command:
              - process_allocator
            resources:
              limits:
                nvidia.com/gpu: "1"
                rdma/ib: "1"
            volumeMounts:
              - name: dshm
                mountPath: /dev/shm
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
